### ISSUE TITLE
Add cookie notice

### ISSUE THREAD

**Issue by dionisisvas** [dionisisvas/training-project#109]
The application should comply with the EU cookie law.

When a user first logs in the application a notice window should show (or a notice bar on top or bottom of the page) notifying him that the application uses cookies. Please check the following link for more information:

https://econsultancy.com/blog/63118-17-useful-examples-of-eu-cookie-law-compliance

**Comment by chris-iri** [comment]
Apparently we fall under [the exceptions](http://ec.europa.eu/ipg/basics/legal/cookies/index_en.htm#section_2)
