### ISSUE TITLE
Create an Edit User page

### ISSUE THREAD

**Issue by dionisisvas** [dionisisvas/training-project#69]
As a user I would like to be able to edit my user details (profile) through a form in a new page.

Prerequisite: Issue #63

The page should show all the user details who is currently logged in a form. The details are fetched from the database. The user should be able to edit the form fields and, by pressing a button, to update his user entry in the database.

* Validations should take place in each form field, similar to the user creation.

* UserId will not be editable.

* A success notification should be shown in case the user was successfully updated in the DB.

* A failure notification should be shown in case the user update is failed.

**Comment by chris-iri** [comment]
Blocked by #81

**Comment by dionisisvas** [comment]
Moving to TO-DO after resolution of issue #81
