### ISSUE TITLE
No auth header sent with REST calls

### ISSUE THREAD

**Issue by chris-iri** [dionisisvas/training-project#81]

**Comment by dionisisvas** [comment]
Please provide detailed description of this bug:
* Steps to reproduce / where to see it
* Current behavior
* Expected behavior

**Comment by chris-iri** [comment]
I've tried to reproduce it today and it is working properly.
It's been a long time since I've implemented JWTs and I don't remember exactly how I've tried to receive the token on the back-end, but I'm assuming I was requesting the wrong header type at the spring controller's parameters, since nothing was changed on how to client handles the tokens.
I'll be adding repro steps next time :)

**Comment by dionisisvas** [comment]
@chris-iri great news!
